#!/usr/bin/env perl

use strict;
use warnings;

use IO::Handle;

sub read_count {
    open my $fh, '<', '/proc/stat' or die "Unreachable: /proc/stat exists";
    while (<$fh>) {
        my @cols = split ' ';
        if (/processes/) {
            close $fh;
            return $cols[1];
        }
    }
    close $fh;
    die 'Unreachable: /proc/stat contains a processes stat';
}

my $count = read_count();
my $total = 0;
my $secs  = 0;

while () {
    sleep 1;
    $secs += 1;

    my $prev_count = $count;
    $count = read_count();
    my $diff = $count - $prev_count;
    $total += $diff;

    printf "%d: %d: %d\n", $secs, $total, $diff;
    STDOUT->flush();
}
